### ISSUE TITLE
Error when compiling `sources/STL-manual.adoc`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-itu#148]
This error is raised when compiling `sources/STL-manual.adoc`.

```
undefined method `+' for nil:NilClass

          label = c.print + (j.zero? ? "" : "#{hierfigsep}#{(96 + j).chr}")
                          ^
gems/3.1.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/xref.rb:110:in `block in sequential_figure_names'
gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:234:in `block in each'
gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `upto'
gems/3.1.0/gems/nokogiri-1.13.8-arm64-darwin/lib/nokogiri/xml/node_set.rb:233:in `each'
gems/3.1.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/xref.rb:104:in `sequential_figure_names'
gems/3.1.0/gems/isodoc-2.2.3.1/lib/isodoc/xref/xref_gen_seq.rb:129:in `sequential_asset_names'
gems/3.1.0/gems/isodoc-2.2.3.1/lib/isodoc/xref/xref_sect_gen.rb:80:in `middle_section_asset_names'
gems/3.1.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/xref.rb:94:in `middle_section_asset_names'
gems/3.1.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/xref.rb:79:in `initial_anchor_names'
gems/3.1.0/gems/isodoc-2.2.3.1/lib/isodoc/xref.rb:62:in `parse'
gems/3.1.0/gems/isodoc-2.2.3.1/lib/isodoc/presentation_xml_convert.rb:17:in `convert1'
gems/3.1.0/gems/isodoc-2.2.3.1/lib/isodoc/convert.rb:224:in `convert'
```

**Comment by ronaldtse** [comment]
This is still a real issue.

**Comment by opoudjis** [comment]
Yes, and I have a backlog. Just alighted on this.

**Comment by opoudjis** [comment]
Unnumbered code snippet, which means that its label is missing, but figure processing is adding subfigure label to the label, if present. 

This was fixed in isodoc, but needs to be fixed in all flavours that customise its behaviour, and have kept old code.
