### ISSUE TITLE
Error when compiling G.191: `undefined method [] for #<IO:<STDOUT>> (NoMethodError)`

### ISSUE THREAD

**Issue by bquast** [metanorma/mn-samples-itu#149]
```
[bquast@Latitude7420 mn-samples-itu]$ metanorma --type itu -x html sources/G.191.adoc 
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[relaton] b-CMake does not have a recognised prefix
[relaton] b-GSM 06.10 does not have a recognised prefix
[relaton] b-STLgit does not have a recognised prefix
[relaton] b-CMake does not have a recognised prefix
[relaton] b-GSM 06.10 does not have a recognised prefix
[relaton] b-STLgit does not have a recognised prefix
Metanorma XML Style Warning: (XML Line 000020): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001401): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003007): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000031): Table should have title
Style: No Keywords have been provided
Metanorma XML Syntax: (XML Line 003143:18): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 003147:18): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 003151:18): element "docidentifier" not allowed yet; missing required element "title"
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSansCJK-Regular.ttc not recognized as a font file.
not a TTC file
Warning: File at /usr/share/fonts/noto/NotoSerifCJK-Regular.ttc not recognized as a font file.
/usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `block in changed?': undefined method `[]' for #<IO:<STDOUT>> (NoMethodError)
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:125:in `changed?'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:120:in `block in do_build_index'
	from <internal:kernel>:90:in `tap'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:119:in `do_build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:108:in `block in build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/utils/locking.rb:11:in `lock'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:107:in `build_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:94:in `index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_index.rb:77:in `find'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:71:in `find_by_index'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:63:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/system_font.rb:52:in `find_styles'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:74:in `find_font_with_name'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/install.rb:16:in `file_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `flat_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `map'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:26:in `call'
	from /usr/lib/ruby/gems/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:47:in `fontist_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:28:in `install_fonts_safe'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:95:in `install_fonts'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile_options.rb:57:in `font_install'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile.rb:36:in `compile'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/command.rb:241:in `compile_document'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/command.rb:47:in `block in compile'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/command.rb:47:in `each'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/command.rb:47:in `compile'
	from /usr/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /usr/lib/ruby/gems/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli.rb:34:in `start'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/exe/metanorma:25:in `block in <top (required)>'
	from /usr/lib/ruby/gems/3.0.0/gems/metanorma-cli-1.6.1/exe/metanorma:43:in `<top (required)>'
	from /usr/bin/metanorma:25:in `load'
	from /usr/bin/metanorma:25:in `<main>'
[bquast@Latitude7420 mn-samples-itu]$ 


```

**Comment by bquast** [comment]
Hello, this is an error I get on ArchLinux. It seems to be LaTeX related? I was trying to export to HTML. I tried on MacOS and didn't get this issue. Any thoughts?

**Comment by bquast** [comment]
I'll try with Darling soon  (takes a while to build) https://www.darlinghq.org/

**Comment by ronaldtse** [comment]
This is a font missing issue. We use a font system called Fontist, it works on several linux flavors but not sure about ArchLinux. Can you try rerunning the command with:

```
metanorma --type itu -x html --agree-to-terms sources/G.191.adoc
```

?

**Comment by ronaldtse** [comment]
@bquast if ArchLinux is the system that you will use, we will need to officially support it as a platform. Is this a case?

**Comment by bquast** [comment]
Dear colleagues,

Thank you for all this work, and taking the time to look at my issue. Indeed I use Arch, but open to use another system. I was just trying to get it running for now. But ITU has given me a Mac Pro to also build these. It would still be good to get it running in general.

I checked the font. Please have a look at the 3 version I have installed (at the bottom of this list)

```
[bquast@Latitude7420 ~]$ yay noto-fonts
33 aur/noto-fonts-variable-ar 20220502-1 (+0 0.00) 
    Google Noto TTF variable fonts for Arabic Scripts
32 aur/ttf-noto-fonts-ib 20170227-1 (+0 0.00) 
    Google Noto TTF fonts
31 aur/noto-fonts-variable-lite 20220607-1 (+0 0.00) 
    Google Noto TTF variable fonts (lite version)
30 aur/noto-fonts-emoji-flags 20200120-1 (+0 0.00) 
    Google Noto emoji fonts with more regional flags
29 aur/noto-fonts-alpha 20180407-2 (+0 0.00) (Orphaned) 
    Alpha versions of Noto fonts.
28 aur/noto-fonts-emoji-flag-git 2.034.r65.g3ee516e14+1.2.1.r1.g0f2ae1a-1 (+0 0.00) 
    Google Noto emoji fonts + extra flags from the fonttools region-flag repo
27 aur/noto-fonts-slim-vf 20220327-1 (+1 0.03) 
    Google Noto variable fonts (limited typefaces coverage)
26 aur/noto-fonts-emoji-lollipop 2015.09.29.license.apache-1 (+1 0.00) 
    Google Noto emoji fonts (Android Lollipop blob version with B&W emoji)
25 aur/ttf-noto-fonts-simple 2017.01.12-2 (+1 0.00) 
    Google Noto TTF fonts
24 aur/noto-fonts-vf 20220327-1 (+1 0.03) 
    Google Noto variable fonts
23 aur/noto-fonts-emoji-git 2:2.028.r0.gc05b4b47c-1 (+1 0.00) 
    Google Noto emoji fonts
22 aur/noto-fonts-main 20210923-1 (+2 0.00) 
    Google Noto fonts: Sans, Sans Display, Sans Mono, Serif, Serif Display
21 aur/noto-fonts-cjk-otf 20170601-3 (+2 0.01) 
    Google Noto CJK fonts, use OTF type to solve some font fallback problems
20 aur/noto-fonts-hk-vf 20220126-5 (+3 0.32) 
    Google Noto Traditional Chinese HK variable fonts
19 aur/noto-fonts-cjk-tc-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts with Traditional Chinese as the default language
18 aur/noto-fonts-cjk-sc-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts with Simplified Chinese as the default language
17 aur/noto-fonts-cjk-jp-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts with Japanese as the default language
16 aur/noto-fonts-cjk-hk-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts with Traditional Chinese HK as the default language
15 aur/noto-fonts-cjk-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts
14 aur/noto-fonts-kr-vf 20220126-5 (+3 0.32) 
    Google Noto Korean variable fonts
13 aur/noto-fonts-sc-vf 20220126-5 (+3 0.32) 
    Google Noto Simplified Chinese variable fonts
12 aur/noto-fonts-tc-vf 20220126-5 (+3 0.32) 
    Google Noto Traditional Chinese variable fonts
11 aur/noto-fonts-jp-vf 20220126-5 (+3 0.32) 
    Google Noto Japanese variable fonts
10 aur/noto-fonts-cjk-kr-vf 20220126-5 (+3 0.32) 
    Google Noto CJK variable fonts with Korean as the default language
9 aur/noto-fonts-tc 2:20201206-1 (+4 0.06) 
    Noto CJK-TC fonts for Traditional Chinese
8 aur/noto-fonts-sc 2:20210430-2 (+8 0.83) 
    Noto CJK-SC fonts for Simplified Chinese
7 aur/noto-fonts-lite 20220607-1 (+8 0.82) 
    Google Noto TTF fonts (lite version)
6 aur/noto-fonts-emoji-apple 1:15.4-4 (+10 1.71) 
    Google Noto emoji fonts replaced with apple branded emoji, modified form a magisk module
5 aur/noto-fonts-emoji-blob 1:14.0.1-1 (+19 0.12) 
    Google Noto emoji fonts (blob version, C1710's fork)
4 extra/noto-fonts-extra 20220607-1 (67.1 MiB 350.2 MiB) (Installed)
    Google Noto TTF fonts - additional variants
3 extra/noto-fonts-emoji 20211101-1 (8.6 MiB 9.4 MiB) 
    Google Noto emoji fonts
2 extra/noto-fonts-cjk 20220126-1 (188.6 MiB 297.8 MiB) (Installed)
    Google Noto CJK fonts
1 extra/noto-fonts 20220607-1 (26.0 MiB 109.7 MiB) (Installed)
    Google Noto TTF fonts
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==> 
 there is nothing to do
[bquast@Latitude7420 ~]$ 
```

**Comment by bquast** [comment]
Ok adding the flag `--agree-to-terms` works:

```
[bquast@Latitude7420 mn-samples-itu]$ metanorma --type itu -x html --agree-to-terms sources/G.191.adoc
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
[relaton] b-CMake does not have a recognised prefix
[relaton] b-GSM 06.10 does not have a recognised prefix
[relaton] b-STLgit does not have a recognised prefix
[relaton] b-CMake does not have a recognised prefix
[relaton] b-GSM 06.10 does not have a recognised prefix
[relaton] b-STLgit does not have a recognised prefix
Metanorma XML Style Warning: (XML Line 000020): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 001401): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 003007): Hanging paragraph in clause
Metanorma XML Style Warning: (XML Line 000031): Table should have title
Style: No Keywords have been provided
Metanorma XML Syntax: (XML Line 003143:18): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 003147:18): element "docidentifier" not allowed yet; missing required element "title"
Metanorma XML Syntax: (XML Line 003151:18): element "docidentifier" not allowed yet; missing required element "title"
[bquast@Latitude7420 mn-samples-itu]$ 
```

How is this. Is there anyway to permanently agree to the terms, to avoid needing the flag?

**Comment by bquast** [comment]
ps. adding this

```
[bquast@Latitude7420 ~]$ cd mn-samples-itu/
[bquast@Latitude7420 mn-samples-itu]$ git status
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	Gemfile.lock
	iev/
	metanorma-itu/
	metanorma-standoc/
	sources/G.191.err
	sources/G.191.html
	sources/G.191.presentation.xml
	sources/Z.100-201811-AnnF1.err

nothing added to commit but untracked files present (use "git add" to track)
[bquast@Latitude7420 mn-samples-itu]$ 
```

**Comment by ronaldtse** [comment]
@bquast 
> How is this. Is there anyway to permanently agree to the terms, to avoid needing the flag?

This output indicates a successful compilation of the document. 

ITU requires the "Times New Roman" and "Courier" fonts for rendering. These fonts are only provided by default on Windows, they typically require additional installation on Linux or macOS (newer macOSes do come with these fonts licensed from Microsoft).

For Linux and macOS, these two fonts are distributed by Microsoft under the "Core Fonts For The Web" package of which usage requires acceptance to Microsoft's terms. More details are available here: https://en.wikipedia.org/wiki/Core_fonts_for_the_Web . 

Metanorma requires the installation of these fonts for ITU, and therefore the flag `--agree-to-terms` is necessary in order to download the fonts that ITU requires on the first run. Once these fonts are installed, the flag is no longer necessary.

Metanorma supports many other SDOs (such as CalConnect, OGC) that use only openly-licensed fonts, such as the Adobe/Google alternatives (Source fonts, Noto fonts) that also provide good readability. In the future, ideally, ITU could adopt openly-licensed fonts.

**Comment by ronaldtse** [comment]
If the necessary fonts (i.e. without passing `--agree-to-terms` are not found by Fontist, Metanorma will use Noto but default, and mn2pdf by default includes Noto:
https://github.com/metanorma/mn2pdf/blob/7b3313c5dd2aa4d724f56aa19ebf9ab29e633e32/src/main/resources/app.properties#L11

In this case, I am not sure why Noto is not dynamically download by mn2pdf on Arch, or why Fontist cannot detect the installed Noto fonts. This requires some research on our end.

**Comment by ronaldtse** [comment]
I suspect that the error shows up when running Arch linux in headless mode, which may have caused the error.

I tried to re-produce the problem on Docker:
```sh
docker run --platform linux/amd64 -it archlinux bash

$ pacman -Sy
$ yes | pacman -Sy git ruby jre-openjdk-headless gcc libffi libxml2 libxslt make
$ PATH="$PATH:$(ruby -e 'puts Gem.user_dir')/bin"
$ gem install metanorma-cli
$ cd /root
$ git clone https://github.com/metanorma/mn-samples-itu.git
$ cd mn-samples-itu
```

```
[root@37f825553e8e mn-samples-itu]# metanorma site generate
[info]: Compiling /root/mn-samples-itu/sources/G.191.adoc ...
[relaton-itu] ("ITU-T G.711") fetching...
...
[relaton] b-STLgit does not have a recognised prefix
...
FONT LICENSE ACCEPTANCE REQUIRED FOR "Arial":

Fontist can install this font if you accept its licensing conditions.

FONT LICENSE BEGIN ("Arial")
-----------------------------------------------------------------------
(from http://web.archive.org/web/20011222020409/http://www.microsoft.com/typography/fontpack/eula.htm)
TrueType core fonts for the Web EULA

END-USER LICENSE AGREEMENT FOR
MICROSOFT SOFTWARE

...
-----------------------------------------------------------------------
FONT LICENSE END ("Arial")

Do you accept all presented font licenses, and want Fontist to download these fonts for you? => TYPE 'Yes' or 'No': Yes
Downloading font "ms_truetype" from https://gitlab.com/fontmirror/archive/-/raw/master/EUupdate.EXE
Downloading: 100% (1/1 MiB), 1.53 MiB/s, done.
Installing font "ms_truetype".
Fonts installed at:
- /root/.fontist/fonts/Arial.ttf
...

FONT LICENSE BEGIN ("Courier New")
-----------------------------------------------------------------------
It is a fact that Linux lacks good high quality fonts for general use. In
the other hand, Microsoft invests time and money to provide a nice and
clean look and feel with high quality fonts like Verdana and Tahoma. The
result of this work is found in their typography
(http://microsoft.com/typography) web site. This is an attempt to give
Linux end users a very easy way to use them, trough an RPM package.

These fonts are free only for who have a Microsoft Windows license.
-----------------------------------------------------------------------
FONT LICENSE END ("Courier New")

Do you accept all presented font licenses, and want Fontist to download these fonts for you? => TYPE 'Yes' or 'No': Yes
Downloading font "opensuse_webcore_fonts" from http://ftp.lysator.liu.se/pub/opensuse/repositories/home:/alteratio:/Common/openSUSE_13.2/src/webcore-fonts-3.0-2.1.src.rpm
Downloading: 100% (7/7 MiB), 2.12 MiB/s, done.
Installing font "opensuse_webcore_fonts".
Fonts installed at:
- /root/.fontist/fonts/WINGDNG2.ttf
...
Downloading font "source" from https://github.com/fontist/source-fonts/releases/download/v1.0/source-fonts-1.0.zip
Downloading: 100% (96/96 MiB), 11.48 MiB/s, done.
Installing font "source".
Fonts installed at:
- /root/.fontist/fonts/SourceCodePro-Black.ttf
...
Downloading font "stix" from https://github.com/stipub/stixfonts/raw/v2.13b171/zipfiles/static_otf.zip
Downloading: 100% (2/2 MiB), 1.06 MiB/s, done.
Installing font "stix".
Fonts installed at:
- /root/.fontist/fonts/STIXTwoMath-Regular.otf
...
java -Xss5m -Xmx2048m -jar /root/.local/share/gem/ruby/3.0.0/gems/mn2pdf-1.50/lib/../bin/mn2pdf.jar --xml-file "/root/mn-samples-itu/site/documents/G.191.presentation.xml" --xsl-file "/root/.local/share/gem/ruby/3.0.0/gems/metanorma-itu-2.1.8.1/lib/isodoc/itu/itu.recommendation.xsl" --pdf-file "/root/mn-samples-itu/site/documents/G.191.pdf" --param baseassetpath="/root/mn-samples-itu/sources" --syntax-highlight  --font-manifest "/tmp/fontist_locations20220919-5813-s4qft6.yml"
```

I was asked 2 times to enter "YES" in order to install the Microsoft fonts. In headless mode, I suspect the prompts don't get displayed properly?

Maybe we need to detect whether there is a terminal attached and then just fail out.

**Comment by ronaldtse** [comment]
As a follow up to this issue, I have created a GitHub Actions build for ArchLinux (#150, #151 ), but the PDFs were not able to be generated.

Unfortunately I am on an Apple M1, which is not supported by Arch Linux Docker images (Arch Linux only supports amd64). Using the amd64 cross-platform Docker image on M1 is hampered by the (probably now well known) serious OpenJDK problem on Docker that hangs Java indefinitely, i.e. I can't generate the PDF step on my machine using Arch Linux.

@Intelligent2013 could you please help check #152 and see if you can generate the PDFs in Arch Linux (using amd64)?

Thanks!

**Comment by maxirmx** [comment]
> Maybe we need to detect whether there is a terminal attached and then just fail out.

If it is 'true' headless mode when there is no terminal attached metanorma terminates with an exception
For example when I run ```nohup metanorma site generate &```  I terminates with
```
Do you accept all presented font licenses, and want Fontist to download these fonts for you? => TYPE 'Yes' or 'No': /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/line_editor/readline.rb:20:in `readline': Bad file descriptor - read (Errno::EBADF)
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/line_editor/readline.rb:20:in `readline'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/line_editor.rb:7:in `readline'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/shell/basic.rb:439:in `ask_simply'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/shell/basic.rb:85:in `ask'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/shell.rb:60:in `ask'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/utils/ui.rb:39:in `ask'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:209:in `ask_for_agreement'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:196:in `check_and_confirm_required_license'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:181:in `request_formula_installation'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:172:in `block in download_font'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:171:in `each'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:171:in `flat_map'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:171:in `download_font'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:56:in `install'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/font.rb:33:in `install'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/install.rb:25:in `install_font'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/install.rb:19:in `file_paths'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:51:in `block in style_paths'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `each'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `flat_map'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:50:in `style_paths'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:45:in `style_paths_map'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:40:in `block in font_paths'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `each'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `map'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:38:in `font_paths'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:26:in `call'
        from /root/.local/share/gem/ruby/3.0.0/gems/fontist-1.14.4/lib/fontist/manifest/locations.rb:21:in `from_hash'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:47:in `fontist_install'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:28:in `install_fonts_safe'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-1.4.14/lib/metanorma/fontist_utils.rb:95:in `install_fonts'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile_options.rb:57:in `font_install'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-1.4.14/lib/metanorma/compile.rb:36:in `compile'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:45:in `compile_file'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:30:in `compile'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/compiler.rb:35:in `compile'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/site_generator.rb:89:in `compile'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/site_generator.rb:29:in `block in generate'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/site_generator.rb:29:in `each'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/site_generator.rb:29:in `generate'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/site_generator.rb:24:in `generate'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli/commands/site.rb:25:in `generate'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:116:in `invoke'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor.rb:243:in `block in subcommand'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /root/.local/share/gem/ruby/3.0.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/lib/metanorma/cli.rb:34:in `start'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/exe/metanorma:25:in `block in <top (required)>'
        from /root/.local/share/gem/ruby/3.0.0/gems/metanorma-cli-1.6.1/exe/metanorma:43:in `<top (required)>'
        from /root/.local/share/gem/ruby/3.0.0/bin/metanorma:25:in `load'
        from /root/.local/share/gem/ruby/3.0.0/bin/metanorma:25:in `<main>'
```

In detached mode like  ```metanorma site generate &```  the process is still attached to the terminal
However, when console io is attempted it terminates with 
```
[5]+  Stopped(SIGTTOU)        metanorma site generate
```

**Comment by maxirmx** [comment]
So, in fontist I will handle SIGTTOU, SIGTTIN  as well as EBADF exception and will fail gracefully

**Comment by ronaldtse** [comment]
@bquast In #153 we have ensured that PDFs generated on Arch Linux are correct:
https://github.com/metanorma/mn-samples-itu/actions/runs/3088899330

See how they look like by downloading the "site" artifact:
<img width="419" alt="Screen Shot 2022-09-21 at 9 28 51 AM" src="https://user-images.githubusercontent.com/11865/191393964-afb54829-a9f6-455c-bdfe-4f87d4738b6c.png">

Please feel free to refer to the necessary prerequisites:

https://github.com/metanorma/mn-samples-itu/blob/b98f1208897fe1ad812b5b016fe30bf201a31528/.github/workflows/archlinux.yml#L19-L26

Closing this issue unless there is anything else to follow up with on Arch Linux. We will also add Arch to the supported list on metanorma.org.

**Comment by ronaldtse** [comment]
> So, in fontist I will handle SIGTTOU, SIGTTIN as well as EBADF exception and will fail gracefully

Thank you @maxirmx !

**Comment by ronaldtse** [comment]
@maxirmx I've created fontist/fontist#305 to handle the Fontist issue.

**Comment by bquast** [comment]
> @bquast In #153 we have ensured that PDFs generated on Arch Linux are correct: https://github.com/metanorma/mn-samples-itu/actions/runs/3088899330
> 
> See how they look like by downloading the "site" artifact: <img alt="Screen Shot 2022-09-21 at 9 28 51 AM" width="419" src="https://user-images.githubusercontent.com/11865/191393964-afb54829-a9f6-455c-bdfe-4f87d4738b6c.png">
> 
> Please feel free to refer to the necessary prerequisites:
> 
> https://github.com/metanorma/mn-samples-itu/blob/b98f1208897fe1ad812b5b016fe30bf201a31528/.github/workflows/archlinux.yml#L19-L26
> 
> Closing this issue unless there is anything else to follow up with on Arch Linux. We will also add Arch to the supported list on metanorma.org.

Thank you very much. That works well for me. Nothing further from my side.

Cheers,
Bastiaan

**Comment by bquast** [comment]
ps. the update pacman repos should be `-Syu` right? not `-Sy` ?

**Comment by ronaldtse** [comment]
@bquast you are likely correct. Thanks!

**Comment by bquast** [comment]
BTW, following this discussion, and a comment by my colleague @maadolph, the TSB (secretariat for ITU-T) made a comment on the new proposed template (for all ITU -R -T and -D Recommendations). We noted that the font proposed was a gratis-free, but not libre-free font, and that this would cause problems. Based on this, the proposed template was modified to use a libre font.

**Comment by ronaldtse** [comment]
@bquast @maadolph the decision to use a libre font would be very welcome! Does the TSB have a particular font in mind? Any font found on [Google Fonts](https://fonts.google.com) would work great.

Ideally, as ITU has 6 official languages, a font that supports all those 6 languages would work best:
* Latin (English, French, Spanish)
* Cyrillic (Russian)
* Arabic
* CJK (Chinese)

However, there is only 1 free font today that supports all of them, which is the "Google Noto" font (also called the "Adobe Source" font). Google Noto is the font used in Android.

Short of that, we would need separate fonts for these language families, which is also not a bad thing (not everyone likes Noto).

For Chinese however, there are rarely any open fonts -- except for Google Noto / Adobe Sans, which is known to be a good and complete choice for their character sets.
